name: 16s-pipeline-2025.7
channels:
  - conda-forge
  - bioconda
dependencies:
  # Python toolchain (no QIIME 2 here)
  - python=3.10
  - mamba=1.5.8
  - pip

  # CLI utilities for automation
  - curl=8.*
  - wget=1.21.*
  - aria2=1.37.*
  - jq=1.7.*
  - yq=3.4.*           # python yq (jq wrapper)
  - parallel>=20240122
  - pigz
  - coreutils
  - unzip
  - tar

  # QC + trimming
  - cutadapt=5.1
  - fastqc=0.12.1
  - multiqc=1.31

  # R + Bioconductor for native DADA2 track
  - r-base=4.4.*
  - r-optparse=1.7.*
  - r-data.table=1.15.*
  - r-tidyverse=2.0.*
  - r-ape=5.*
  - r-vegan=2.6.*
  - bioconductor-dada2=1.34.0
  - bioconductor-phyloseq=1.50.0
  - bioconductor-decipher=2.32.*
  - bioconductor-genomeinfodbdata=1.2.13
  - bioconductor-biostrings=2.72.*
