name: CI
on: [push, pull_request]
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          cache-environment: true
          cache-downloads: true
      - name: Bootstrap QIIME 2
        shell: bash -l {0}
        run: bash run.sh --bootstrap-qiime2
      - name: Run tiny test (wire to your small dataset)
        shell: bash -l {0}
        run: bash run.sh -c config/config.yaml
